# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'suncoast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for suncoast
  pod 'OpenTok'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end
